### ISSUE TITLE
Policy

### ISSUE THREAD

**Issue by lloricode** [joshgaber/NovaUnit#49]
Hi, is there a policy or gate assert for this? or check if the resource can  or cannot access specific part by specific user?

**Comment by joshgaber** [comment]
No, this library doesn't support assertions around Laravel's policies and gate configurations, but I'm not opposed to adding them if someone wants to write those assertions.

**Comment by lloricode** [comment]
ok thank you, will try to figure out if a can make add an `PolicyAssertions` trait for `MockResource`
